<a href="https://colab.research.google.com/github/adityasahu88/PROJECT/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Dropout,Activation
from tensorflow.keras.optimizers import SGD,Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.activations import relu,sigmoid,softmax
import sys



In [13]:
# generate 1000 rows and 24 columns using random
class ANN_data_generator:

  def __init__(self):
    try:
       self.model =None
       print("Initalize the object")

    except Exception as e:
      error_type,err_msg,error_line_no= sys.exc_info()
      print(f"The error msg is {err_msg} and in Line No {error_line_no.tb_lineno}")

  def get_data(self):
      np.random.seed(42)
      df_features =pd.DataFrame(np.random.random((1000,24)),columns=[str(i)+'A' for i in range(1,25)])
      # generate target colunms where first 400 classes will be 0th class,300 classes will be 1st class and 300 will be 300 2ns classes
      list_class = [0 for i in range(0,400)]+[1 for i in range(400,700)]+[2 for i in range(700,1000)]
      df_target = pd.DataFrame(list_class,columns=['target'])
      # Concat  the features and target columns to make the final data
      df =pd.concat([df_features,df_target],axis=1)
      return df




  def train_test_split(self,df):
    try :
      X= df.drop('target',axis=1)
      y=df['target']
      X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
      return X_train,X_test,y_train,y_test
    except Exception as e:
      error_type,err_msg,error_line_no= sys.exc_info()
      print(f"The error msg is {err_msg} and in Line No {error_line_no.tb_lineno}")

  def ann_model_training(self,X_train,y_train):
    try :
      self.model=Sequential()
      self.model.add(Dense(128,activation='relu',input_dim=X_train.shape[1]))
      self.model.add(Dense(64,activation='relu'))
      self.model.add(Dense(32,activation='relu'))
      self.model.add(Dense(3,activation='softmax'))
      self.model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
      self.model.fit(X_train,y_train,epochs=50,batch_size=20,validation_split=0.2)
      return(self.model.summary())

    except Exception as e:
      error_type,err_msg,error_line_no = sys.exc_info()
      print(f"The error msg is {err_msg} and in Line No {error_line_no.tb_lineno}")

  def ann_model_testing(self,X_test,y_test):
        try:
            y_pred = self.model.predict(X_test)
            y_pred_classes =np.argmax(y_pred,axis=1)
            print(classification_report(y_test,y_pred_classes))
            print(confusion_matrix(y_test,y_pred_classes))
            print(accuracy_score(y_test,y_pred_classes))
        except Exception as e:
            er_type, er_msg, line_no = sys.exc_info()
            print(f'Error in line no: {line_no.tb_lineno} and Error Message: {er_msg}')


if __name__=='__main__':
  try :
    obj=ANN_data_generator()
    print("=================Object Initialize done===================")
    df=obj.get_data()
    print("=================Data generated Successfully===================")
    X_train,X_test,y_train,y_test=obj.train_test_split(df)
    print("=================Data Train Test Split Successfully===================")
    model=obj.ann_model_training(X_train,y_train)
    print("=================Data Train Model Successfully===================")
    obj.ann_model_testing(X_test,y_test)
    print("=================Data Test Model Successfully===================")
  except Exception as e:
    error_type,err_msg,error_line_no= sys.exc_info()
    print(f"The error msg is {err_msg} and in Line No {error_line_no.tb_lineno}")






Initalize the object
=================Object Initialize done===================
=================Data generated Successfully===================
=================Data Train Test Split Successfully===================
Epoch 1/50
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.3893 - loss: 1.0946 - val_accuracy: 0.4187 - val_loss: 1.0965
Epoch 2/50
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3802 - loss: 1.1000 - val_accuracy: 0.4250 - val_loss: 1.0842
Epoch 3/50
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4069 - loss: 1.0804 - val_accuracy: 0.3812 - val_loss: 1.0926
Epoch 4/50
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4532 - loss: 1.0706 - val_accuracy: 0.4000 - val_loss: 1.0842
Epoch 5/50
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4381 - loss: 1.0563 - val_accuracy: 0.4000 - val_loss: 1.1055
Epoch 6/50
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4582 - loss: 1.0552 - val_accuracy: 0.3875 - val_loss: 1.0890
Epoch 7/50
32/32 ━━━━━━━━━━━━

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_28 (Dense)                     │ (None, 128)                 │           3,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_29 (Dense)                     │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_30 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_31 (Dense)                     │ (None, 3)                   │              99 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 40,907 (159.80 KB)

 Trainable params: 13,635 (53.26 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 27,272 (106.54 KB)

=================Data Train Model Successfully===================
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
              precision    recall  f1-score   support

           0       0.36      0.31      0.33        81
           1       0.30      0.31      0.30        62
           2       0.21      0.25      0.23        57

    accuracy                           0.29       200
   macro avg       0.29      0.29      0.29       200
weighted avg       0.30      0.29      0.29       200

[[25 23 33]
 [24 19 19]
 [21 22 14]]
0.29
=================Data Test Model Successfully===================
